Sorry: IndentationError: expected an indented block (waypoints_logger.py, line 27)
